version: '3'

services:
  ansible:
    image: iodaud/ansible-app:4
    build:
      context: ansible
    working_dir: /app
    command: node index.js
    ports:
      - "8012:8012"
      - "8013:8013"
    
  web:
    image: iodaud/ansible-web:4
    restart: always
    build:
      context: web
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./web:/usr/share/nginx/html
